package us.secureapps.gotech.model;

import javax.annotation.Generated;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@Generated(value="Dali", date="2014-06-28T21:23:42.523-0400")
@StaticMetamodel(NonProd.class)
public class NonProd_ {
    public static volatile SingularAttribute<NonProd, Integer> id;
    public static volatile SingularAttribute<NonProd, String> api;
    public static volatile SingularAttribute<NonProd, Integer> co2vol1;
    public static volatile SingularAttribute<NonProd, Integer> co2vol10;
    public static volatile SingularAttribute<NonProd, Integer> co2vol11;
    public static volatile SingularAttribute<NonProd, Integer> co2vol12;
    public static volatile SingularAttribute<NonProd, Integer> co2vol2;
    public static volatile SingularAttribute<NonProd, Integer> co2vol3;
    public static volatile SingularAttribute<NonProd, Integer> co2vol4;
    public static volatile SingularAttribute<NonProd, Integer> co2vol5;
    public static volatile SingularAttribute<NonProd, Integer> co2vol6;
    public static volatile SingularAttribute<NonProd, Integer> co2vol7;
    public static volatile SingularAttribute<NonProd, Integer> co2vol8;
    public static volatile SingularAttribute<NonProd, Integer> co2vol9;
    public static volatile SingularAttribute<NonProd, Integer> countyID;
    public static volatile SingularAttribute<NonProd, Integer> daysprod1;
    public static volatile SingularAttribute<NonProd, Integer> daysprod10;
    public static volatile SingularAttribute<NonProd, Integer> daysprod11;
    public static volatile SingularAttribute<NonProd, Integer> daysprod12;
    public static volatile SingularAttribute<NonProd, Integer> daysprod2;
    public static volatile SingularAttribute<NonProd, Integer> daysprod3;
    public static volatile SingularAttribute<NonProd, Integer> daysprod4;
    public static volatile SingularAttribute<NonProd, Integer> daysprod5;
    public static volatile SingularAttribute<NonProd, Integer> daysprod6;
    public static volatile SingularAttribute<NonProd, Integer> daysprod7;
    public static volatile SingularAttribute<NonProd, Integer> daysprod8;
    public static volatile SingularAttribute<NonProd, Integer> daysprod9;
    public static volatile SingularAttribute<NonProd, Integer> gasvol1;
    public static volatile SingularAttribute<NonProd, Integer> gasvol10;
    public static volatile SingularAttribute<NonProd, Integer> gasvol11;
    public static volatile SingularAttribute<NonProd, Integer> gasvol12;
    public static volatile SingularAttribute<NonProd, Integer> gasvol2;
    public static volatile SingularAttribute<NonProd, Integer> gasvol3;
    public static volatile SingularAttribute<NonProd, Integer> gasvol4;
    public static volatile SingularAttribute<NonProd, Integer> gasvol5;
    public static volatile SingularAttribute<NonProd, Integer> gasvol6;
    public static volatile SingularAttribute<NonProd, Integer> gasvol7;
    public static volatile SingularAttribute<NonProd, Integer> gasvol8;
    public static volatile SingularAttribute<NonProd, Integer> gasvol9;
    public static volatile SingularAttribute<NonProd, String> leaseid;
    public static volatile SingularAttribute<NonProd, String> nonProductionYears;
    public static volatile SingularAttribute<NonProd, Integer> oilvol1;
    public static volatile SingularAttribute<NonProd, Integer> oilvol10;
    public static volatile SingularAttribute<NonProd, Integer> oilvol11;
    public static volatile SingularAttribute<NonProd, Integer> oilvol12;
    public static volatile SingularAttribute<NonProd, Integer> oilvol2;
    public static volatile SingularAttribute<NonProd, Integer> oilvol3;
    public static volatile SingularAttribute<NonProd, Integer> oilvol4;
    public static volatile SingularAttribute<NonProd, Integer> oilvol5;
    public static volatile SingularAttribute<NonProd, Integer> oilvol6;
    public static volatile SingularAttribute<NonProd, Integer> oilvol7;
    public static volatile SingularAttribute<NonProd, Integer> oilvol8;
    public static volatile SingularAttribute<NonProd, Integer> oilvol9;
    public static volatile SingularAttribute<NonProd, Integer> poolid;
    public static volatile SingularAttribute<NonProd, String> poolname;
    public static volatile SingularAttribute<NonProd, Integer> proddate;
    public static volatile SingularAttribute<NonProd, String> status1;
    public static volatile SingularAttribute<NonProd, String> status10;
    public static volatile SingularAttribute<NonProd, String> status11;
    public static volatile SingularAttribute<NonProd, String> status12;
    public static volatile SingularAttribute<NonProd, String> status2;
    public static volatile SingularAttribute<NonProd, String> status3;
    public static volatile SingularAttribute<NonProd, String> status4;
    public static volatile SingularAttribute<NonProd, String> status5;
    public static volatile SingularAttribute<NonProd, String> status6;
    public static volatile SingularAttribute<NonProd, String> status7;
    public static volatile SingularAttribute<NonProd, String> status8;
    public static volatile SingularAttribute<NonProd, String> status9;
    public static volatile SingularAttribute<NonProd, Integer> watervol1;
    public static volatile SingularAttribute<NonProd, Integer> watervol10;
    public static volatile SingularAttribute<NonProd, Integer> watervol11;
    public static volatile SingularAttribute<NonProd, Integer> watervol12;
    public static volatile SingularAttribute<NonProd, Integer> watervol2;
    public static volatile SingularAttribute<NonProd, Integer> watervol3;
    public static volatile SingularAttribute<NonProd, Integer> watervol4;
    public static volatile SingularAttribute<NonProd, Integer> watervol5;
    public static volatile SingularAttribute<NonProd, Integer> watervol6;
    public static volatile SingularAttribute<NonProd, Integer> watervol7;
    public static volatile SingularAttribute<NonProd, Integer> watervol8;
    public static volatile SingularAttribute<NonProd, Integer> watervol9;
    public static volatile SingularAttribute<NonProd, Integer> wellnumb;
}
